### ISSUE TITLE
todo-courses

### ISSUE THREAD

**Issue by Ab2nour** [IAntoineV/LearningAI#1]
This issue contains our ideas of courses to create

# Maths
- [ ] Intro Graph1
- [ ] Intro Graph2
- [ ] Stats

# Machine Learning
- [ ] create your own Random Forest 
- [ ] Dimension reductions
- [ ] clustering
- [ ] Data processing (outliers detections, normalization, one hot, pipelines)
- [ ] Data augmentation

# Deep Learning
- [ ] Dense
- [ ] Optimizers (Adam)
- [ ] Regularisation (dropout, L2, L1, other)
- [ ] Training speed / stability (LR effect on speed and results) 
- [ ] CNN
- [ ] Common image processing architecture (U-net et autre)
- [ ] RNN
- [ ] Transformers
- [ ] NLP
- [ ] Diffusion
- [ ] Unsupervised
- [ ] Adversarial attack (maybe use it as a data augmentation method)

# Reinforcement Learning
- [ ] RL basics
- [ ] Diving into SB3
- [ ] Q Learning
- [ ] Deep Q learning
- [ ] Create our own environment

# Data vizualisation
- [ ] Dash1 : create a simple dashboard with Dash
- [ ] Dash2 : Mini web app
- [ ] plot training curves with TensorBoard
- [ ] Use of dimension reduction techniques (PCA, Kernel PCA, UMAP)

# Project management
- [ ] How to manage the structure of a data science project
- [ ] How to manage Data in a data science project
- [ ] Code quality check
- [ ] virtual environment / dependencies
- [ ] Continuous integration (CI)
- [ ] How to use git
- [ ] How to use sphinx
  - [ ] Go further : interaction sphinx / github + README integration
